-- liquibase formatted sql

CREATE TABLE "ORDER"
(
	"ID" UUID PRIMARY KEY
);

CREATE TABLE "ORDER_ITEM"
(
	"ORDER_ID"    UUID NOT NULL,
	"PRODUCT_REF" UUID NOT NULL,
	"QUANTITY"    INT  NOT NULL,
	PRIMARY KEY ("ORDER_ID", "PRODUCT_REF"),
	FOREIGN KEY ("ORDER_ID") REFERENCES "ORDER" ("ID") ON DELETE CASCADE
);

CREATE TABLE "INVENTORY"
(
	"PRODUCT_REF" UUID PRIMARY KEY,
	"QUANTITY"    INT  NOT NULL
);

